# Generated by Django 4.2.5 on 2023-11-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
