# Generated by Django 4.2.5 on 2023-11-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_checkout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='tot',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartlist',
            name='discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartlist',
            name='gt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
