# Generated by Django 4.2.5 on 2023-11-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cartitem_tot_cartlist_discount_cartlist_gt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='tot',
        ),
    ]
