# Generated by Django 4.2.5 on 2023-11-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_cartitem_tot'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='tot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
