# Generated by Django 4.2.5 on 2023-11-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_rename_tot_cartitem_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartlist',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartlist',
            name='gt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
