# Generated by Django 4.2.5 on 2023-11-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_cartlist_discount_alter_cartlist_gt'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartlist',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
