# Generated by Django 4.2.5 on 2023-11-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_cartlist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartlist',
            name='status',
            field=models.CharField(default='carted', max_length=100),
        ),
    ]
