# Generated by Django 4.2.5 on 2023-11-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_remove_cartlist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartlist',
            name='status',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
