# Generated by Django 4.2.5 on 2023-09-11 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=250, unique=True)),
                ('image', models.ImageField(upload_to='products')),
                ('description', models.TextField()),
                ('stock', models.IntegerField()),
                ('availablility', models.BooleanField()),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.category')),
            ],
        ),
    ]
