# Generated by Django 4.2.5 on 2023-09-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_prducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='prducts',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
